erDiagram
    SERIES {
        String doi "P10 DOI"
        WikibaseItem instance_of "P1 Q4"
    }
    CHAPTER {
        String doi "P10 DOI"
        WikibaseItem instance_of "P1 Q6"
    }
    SERIES ||--|{ CHAPTER : "contains"
