<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ar6-quantification-protocol – ClimateKG Data Bench</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.plot.ly/plotly-latest.min.js" charset="utf-8"></script>
<script>
document.addEventListener("DOMContentLoaded", function () {
  var siteHeader = document.querySelector("body > header");
  var existing = document.querySelector(".site-strapline");
  if (!siteHeader || existing) {
    return;
  }

  var strapline = document.createElement("div");
  strapline.className = "site-strapline";
  strapline.setAttribute("role", "note");
  strapline.innerHTML = "<div class=\"site-strapline-inner\">A community portal for working on the Climate Knowledge Graph</div>";
  siteHeader.insertAdjacentElement("afterend", strapline);
});
</script>


<link rel="stylesheet" href="../../styles/footer-accessibility.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ClimateKG Data Bench</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../get-involved.html"> 
<span class="menu-text">Get Involved!</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../knowledge-graph.html"> 
<span class="menu-text">Knowledge Graph</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-analysis">    
        <li>
    <a class="dropdown-item" href="../../research_data/data-vis/gender-distribution-simple.html">
 <span class="dropdown-text">AR6 Author Distribution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/data-vis/authors-top-ten.html">
 <span class="dropdown-text">Top 10 Global South Authors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/data-vis/buildings-urban-chapters.html">
 <span class="dropdown-text">Buildings &amp; Urban</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sparql_queries/class-counts.html">
 <span class="dropdown-text">Class Instance Counts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sparql_queries/investigate-q1-count.html">
 <span class="dropdown-text">Investigation: Q1 Count Discrepancy</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/TIBHannover/Climate-KG-data/tree/main/sparql_queries">
 <span class="dropdown-text">View Notebooks on GitHub</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="../../about-data.html">
 <span class="dropdown-text">About Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../xml-html-documentation.html">
 <span class="dropdown-text">XML/HTML Pipeline Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/data-vis/kg-stats-dashboard.html">
 <span class="dropdown-text">ClimateKG Dashboard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/rdp/ar6-quantification-protocol.html">
 <span class="dropdown-text">Research Data Protocol</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Generated Data Pages</li>
        <li>
    <a class="dropdown-item" href="../../data/authors-ar6.html">
 <span class="dropdown-text">Authors Directory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../data/acronyms-ar6.html">
 <span class="dropdown-text">Acronyms Index</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../data/bibliographic-ar6.html">
 <span class="dropdown-text">Bibliography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../data/corpus-ar6.html">
 <span class="dropdown-text">Corpus Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../data/glossary-ar6.html">
 <span class="dropdown-text">Glossary</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-er-model" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">ER Model</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-er-model">    
        <li>
    <a class="dropdown-item" href="../../er-model.html">
 <span class="dropdown-text">ER model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/data-xml-dtd/erm/erm-diagram.html">
 <span class="dropdown-text">Wikibase ERM Diagram</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research_data/data-xml-dtd/erm/README.html">
 <span class="dropdown-text">ER Model Documentation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-software" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Software</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-software">    
        <li>
    <a class="dropdown-item" href="../../software.html">
 <span class="dropdown-text">Software</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ckg-scrape.html">
 <span class="dropdown-text">CKG Scrape</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ckg-data.html">
 <span class="dropdown-text">CKG Data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-data-protocol-quantifying-the-ar6-reports" id="toc-research-data-protocol-quantifying-the-ar6-reports" class="nav-link active" data-scroll-target="#research-data-protocol-quantifying-the-ar6-reports">Research Data Protocol: Quantifying the AR6 Reports</a>
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#scope" id="toc-scope" class="nav-link" data-scroll-target="#scope">Scope</a>
  <ul class="collapse">
  <li><a href="#in-scope-the-7-main-reports-of-ar6" id="toc-in-scope-the-7-main-reports-of-ar6" class="nav-link" data-scroll-target="#in-scope-the-7-main-reports-of-ar6">In scope: the 7 main reports of AR6</a></li>
  <li><a href="#out-of-scope" id="toc-out-of-scope" class="nav-link" data-scroll-target="#out-of-scope">Out of scope</a></li>
  </ul></li>
  <li><a href="#stats-collected" id="toc-stats-collected" class="nav-link" data-scroll-target="#stats-collected">Stats collected</a></li>
  <li><a href="#pdf-page-count-and-word-count" id="toc-pdf-page-count-and-word-count" class="nav-link" data-scroll-target="#pdf-page-count-and-word-count">1. PDF page count and word count</a></li>
  <li><a href="#pdf-licensing-information-and-dois" id="toc-pdf-licensing-information-and-dois" class="nav-link" data-scroll-target="#pdf-licensing-information-and-dois">2. PDF licensing information and DOIs</a></li>
  <li><a href="#citations-references-bibtex-downloads-reference-counts" id="toc-citations-references-bibtex-downloads-reference-counts" class="nav-link" data-scroll-target="#citations-references-bibtex-downloads-reference-counts">3. Citations / references (BibTeX downloads, reference counts)</a></li>
  <li><a href="#author-counts" id="toc-author-counts" class="nav-link" data-scroll-target="#author-counts">4. Author counts</a></li>
  <li><a href="#wikidata-entries-of-ar6-reports" id="toc-wikidata-entries-of-ar6-reports" class="nav-link" data-scroll-target="#wikidata-entries-of-ar6-reports">5. Wikidata entries of AR6 reports</a></li>
  <li><a href="#figures-count" id="toc-figures-count" class="nav-link" data-scroll-target="#figures-count">6. Figures count</a></li>
  <li><a href="#data-count" id="toc-data-count" class="nav-link" data-scroll-target="#data-count">7. Data count</a></li>
  <li><a href="#glossary-term-count" id="toc-glossary-term-count" class="nav-link" data-scroll-target="#glossary-term-count">8. Glossary term count</a></li>
  <li><a href="#report-translations" id="toc-report-translations" class="nav-link" data-scroll-target="#report-translations">9. Report translations</a></li>
  <li><a href="#acronyms-count" id="toc-acronyms-count" class="nav-link" data-scroll-target="#acronyms-count">10. Acronyms count</a></li>
  <li><a href="#index-terms-count" id="toc-index-terms-count" class="nav-link" data-scroll-target="#index-terms-count">11. Index terms count</a></li>
  <li><a href="#update-log" id="toc-update-log" class="nav-link" data-scroll-target="#update-log">Update log</a></li>
  <li><a href="#open-follow-up-work" id="toc-open-follow-up-work" class="nav-link" data-scroll-target="#open-follow-up-work">Open follow-up work</a></li>
  <li><a href="#related-repository-content" id="toc-related-repository-content" class="nav-link" data-scroll-target="#related-repository-content">Related repository content</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="research-data-protocol-quantifying-the-ar6-reports" class="level1">
<h1>Research Data Protocol: Quantifying the AR6 Reports</h1>
<p><strong>Source issue:</strong> <a href="https://github.com/TIBHannover/climate-knowledge-graph/issues/18">TIBHannover/climate-knowledge-graph#18 — Quantifying the AR6 Reports and Data Protocol</a></p>
<p><strong>Status:</strong> Ongoing / partially automated (see <a href="#update-log">Update log</a> and <a href="#open-follow-up-work">Open follow-up work</a>)</p>
<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>This protocol documents how document- and bibliographic-level statistics were gathered for the scientific text corpus that makes up the IPCC Sixth Assessment Report (AR6). It records, for each metric, what was counted, where the source data came from, the method used to collect it, and known limitations, so that the counts can be reproduced, corrected, or automated in future work.</p>
</section>
<section id="scope" class="level2">
<h2 class="anchored" data-anchor-id="scope">Scope</h2>
<section id="in-scope-the-7-main-reports-of-ar6" class="level3">
<h3 class="anchored" data-anchor-id="in-scope-the-7-main-reports-of-ar6">In scope: the 7 main reports of AR6</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Short code</th>
<th>Report</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>AR6 Synthesis Report: Climate Change 2023</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>Climate Change 2021: The Physical Science Basis (Working Group I)</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>Climate Change 2022: Impacts, Adaptation and Vulnerability (Working Group II)</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>Climate Change 2022: Mitigation of Climate Change (Working Group III)</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>Special Report: Global Warming of 1.5°C (2018)</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>Special Report: Climate Change and Land (2019)</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>Special Report: The Ocean and Cryosphere in a Changing Climate (2019)</td>
</tr>
</tbody>
</table>
</section>
<section id="out-of-scope" class="level3">
<h3 class="anchored" data-anchor-id="out-of-scope">Out of scope</h3>
<ul>
<li><em>2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories</em> (the Methodology Report belonging to the AR6 cycle, but not treated as one of the main reports for this protocol).</li>
</ul>
</section>
</section>
<section id="stats-collected" class="level2">
<h2 class="anchored" data-anchor-id="stats-collected">Stats collected</h2>
<ol type="1">
<li>PDF page count and word count</li>
<li>PDF licensing information and DOIs</li>
<li>Citations / references (BibTeX downloads, reference counts)</li>
<li>Author counts</li>
<li>Wikidata entries of AR6 reports</li>
<li>Figures count</li>
<li>Data count (datasets / data access points)</li>
<li>Glossary term count</li>
<li>Report translations</li>
<li>Acronyms count</li>
<li>Index terms count</li>
</ol>
<hr>
</section>
<section id="pdf-page-count-and-word-count" class="level2">
<h2 class="anchored" data-anchor-id="pdf-page-count-and-word-count">1. PDF page count and word count</h2>
<p><strong>Method</strong></p>
<ul>
<li>File size: read directly from the PDF file properties (Finder/Explorer).</li>
<li>Page count: read from the PDF file. Counted only the numbered pages of the report body (a first pass mistakenly added the roman-numeral front-matter pages on top of the page count; this was corrected in the June 2026 update, see below).</li>
<li>Word count: original pass — copy-pasted PDF text into <a href="https://wordcounter.net/">wordcounter.net</a> (“Basic Option”). Revised pass (June 2026) — opened the PDF in Chrome and used the “Word Count Counter Plus” browser extension.</li>
</ul>
<p><strong>Known limitations</strong></p>
<ul>
<li>Word counts are rough estimates: front matter, footers, references, and other non-body text were not stripped out before counting.</li>
<li>Clipboard-based counting was unreliable for very large documents.</li>
<li>Figures reported below are rounded and, in places, have been superseded by a corrected figure recorded alongside the original (shown as <code>original → corrected</code>).</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Report</th>
<th>Source file / URL</th>
<th>File size</th>
<th>Page count</th>
<th>Word count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td><code>IPCC_AR6_SYR_FullVolume.pdf</code> — https://www.ipcc.ch/report/ar6/syr/</td>
<td>4.9 MB</td>
<td>185 + 14 pages</td>
<td>~94,000 → 93,806</td>
</tr>
<tr class="even">
<td>WGI</td>
<td><code>IPCC_AR6_WGI_FullReport.pdf</code> — https://www.ipcc.ch/report/ar6/wg1/</td>
<td>423.3 MB</td>
<td>2,409 pages</td>
<td>~1,925,000 → 1,925,469</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td><code>IPCC_AR6_WGII_FullReport.pdf</code> — https://www.ipcc.ch/report/ar6/wg2/</td>
<td>396 MB</td>
<td>3,068 + 12 pages</td>
<td>~2,513,000 → 2,514,759</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td><code>IPCC_AR6_WGIII_FullReport.pdf</code> — https://www.ipcc.ch/report/ar6/wg3/</td>
<td>68.8 MB</td>
<td>2,042 + 11 pages</td>
<td>~1,642,000 → 1,642,687</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td><code>SR15_Full_Report_HR.pdf</code> — https://www.ipcc.ch/sr15/</td>
<td>65 MB</td>
<td>631 pages</td>
<td>~511,000 → 510,684</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td><code>SRCCL_Full_Report.pdf</code> — https://www.ipcc.ch/srccl/</td>
<td>44.9 MB</td>
<td>908 pages</td>
<td>~735,000 → 734,356</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td><code>SROCC_FullReport_FINAL.pdf</code> — https://www.ipcc.ch/srocc/</td>
<td>51.9 MB</td>
<td>766 pages</td>
<td>~627,000 → 627,209</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td><strong>1,054.8 MB</strong></td>
<td><strong>10,009 pages</strong></td>
<td><strong>~8,047,000 → 8,048,970</strong></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="pdf-licensing-information-and-dois" class="level2">
<h2 class="anchored" data-anchor-id="pdf-licensing-information-and-dois">2. PDF licensing information and DOIs</h2>
<p><strong>Method</strong></p>
<ul>
<li>DOIs: retrieved from the front matter of each PDF.</li>
<li>DOIs resolved via <a href="https://doi.org">doi.org</a> to confirm the target and licence.</li>
</ul>
<p><strong>Summary</strong></p>
<ul>
<li>SYR: covered by the general <a href="https://www.ipcc.ch/copyright/">IPCC copyright statement</a> — no report-specific licence was found.</li>
<li>WGI, WGII, WGIII, SR1.5, SRCCL, SROCC: <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en">CC BY-NC-ND 4.0</a>.</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Report</th>
<th>DOI</th>
<th>Report page</th>
<th>Licence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>10.59327/IPCC/AR6-9789291691647</td>
<td>https://www.ipcc.ch/report/ar6/syr/</td>
<td>https://www.ipcc.ch/copyright/</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>10.1017/9781009157896</td>
<td><a href="https://www.cambridge.org/core/books/climate-change-2021-the-physical-science-basis/415F29233B8BD19FB55F65E3DC67272B">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>10.1017/9781009325844</td>
<td><a href="https://www.cambridge.org/core/books/climate-change-2022-impacts-adaptation-and-vulnerability/161F238F406D530891AAAE1FC76651BD">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>10.1017/9781009157926</td>
<td><a href="https://www.cambridge.org/core/books/climate-change-2022-mitigation-of-climate-change/2929481A59B59C57C743A79420A2F9FF">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>10.1017/9781009157940</td>
<td><a href="https://www.cambridge.org/core/books/global-warming-of-15c/D7455D42B4C820E706A03A169B1893FA">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>10.1017/9781009157988</td>
<td><a href="https://www.cambridge.org/core/books/climate-change-and-land/AAB03E2F17650B1FDEA514E3F605A685">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>10.1017/9781009157964</td>
<td><a href="https://www.cambridge.org/core/books/ocean-and-cryosphere-in-a-changing-climate/A05E6C9F8638FA7CE1748DE2EB7B491B">Cambridge Core</a></td>
<td>CC BY-NC-ND 4.0</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="citations-references-bibtex-downloads-reference-counts" class="level2">
<h2 class="anchored" data-anchor-id="citations-references-bibtex-downloads-reference-counts">3. Citations / references (BibTeX downloads, reference counts)</h2>
<p><strong>Method</strong></p>
<ul>
<li><code>.bib</code> file count: counted manually on each report’s website under Chapters/Annexes → “Downloads” → “Citations (bib)”. Flagged as needing revisiting since it was a manual count.</li>
<li>Reference / citation counts: no single authoritative source exists per report, so multiple secondary sources were gathered and cross-checked (see below). Figures should be treated as estimates, not exact counts.</li>
</ul>
<p><strong>Reference collection</strong></p>
<ul>
<li>Zotero group collection: https://www.zotero.org/groups/2437020/semanticclimate/collections/LJKWTTYZ</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Report</th>
<th><code>.bib</code> files</th>
<th>Estimated references/citations</th>
<th>Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>0 (no citations/references in this report)</td>
<td>0?</td>
<td>—</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>~13</td>
<td>13,000–19,266</td>
<td><a href="https://en.wikipedia.org/wiki/IPCC_Sixth_Assessment_Report#WG1report">Wikipedia</a> (&gt;14,000 papers); <a href="https://zenodo.org/records/7615825">Zenodo analysis</a> (&gt;18,000 citations / &gt;13,000 unique refs); <a href="https://www.carbonbrief.org/guest-post-what-13500-citations-reveal-about-the-ipccs-climate-science-report/">Carbon Brief</a> (13,500); <a href="https://theconversation.com/234-scientists-read-14-000-research-papers-to-write-the-ipcc-climate-report-heres-what-you-need-to-know-and-why-its-a-big-deal-165587">The Conversation</a> (14,000); <a href="https://zenodo.org/records/5475442">Zenodo record</a> (19,266 distinct reference strings)</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>~29</td>
<td>17,419</td>
<td><a href="https://en.wikipedia.org/wiki/IPCC_Sixth_Assessment_Report#Working_Group_2_report_(impacts,_adaptation_and_vulnerability)">Wikipedia</a>; <a href="https://zenodo.org/records/6344388">Zenodo</a> (17,419 DOIs cited)</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>~19</td>
<td>? (not yet resolved)</td>
<td><a href="https://en.wikipedia.org/wiki/IPCC_Sixth_Assessment_Report#Working_Group_3_report_(mitigation_of_climate_change)">Wikipedia</a></td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>none found</td>
<td>5,000–6,099</td>
<td><a href="https://en.wikipedia.org/wiki/Special_Report_on_Global_Warming_of_1.5_%C2%B0C">Wikipedia</a> (&gt;6,000 references, 91 authors, 40 countries); <a href="https://zenodo.org/records/5475442">Zenodo</a> (5,099 distinct reference strings)</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>none found</td>
<td>7,800–7,828</td>
<td><a href="https://en.wikipedia.org/wiki/Special_Report_on_Climate_Change_and_Land">Wikipedia</a>; <a href="https://zenodo.org/records/5475442">Zenodo</a> (7,828 distinct reference strings)</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>none found</td>
<td>6,981–7,161</td>
<td><a href="https://en.wikipedia.org/wiki/Special_Report_on_the_Ocean_and_Cryosphere_in_a_Changing_Climate">Wikipedia</a> (6,981 publications, 104 authors, 36 countries); <a href="https://www.centrescientifique.mc/en/article/the-special-report-on-the-ocean-and-cryosphere-in-a-changing-climate-srocc-accepted">Centre Scientifique de Monaco</a> (6,981 cited references); <a href="https://zenodo.org/records/5475442">Zenodo</a> (7,161 distinct reference strings)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="author-counts" class="level2">
<h2 class="anchored" data-anchor-id="author-counts">4. Author counts</h2>
<p><strong>Method</strong></p>
<ul>
<li>Counted from the “authors” listing published on each report’s landing page, and cross-checked against the <a href="https://apps.ipcc.ch/report/authors/authors.php">IPCC authors app</a>.</li>
<li>Duplicates (an author contributing to multiple reports) are <strong>not</strong> consolidated in the per-report table below — the same person is counted once per report they contributed to.</li>
<li>June 2026 update: all authors were collected into a spreadsheet and de-duplicated using an LLM (Claude), matching on Last name + First name → merge. This produced a de-duplicated total of <strong>932 unique authors</strong> across all seven reports.</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Report</th>
<th>Source</th>
<th>Authors</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td><a href="https://www.ipcc.ch/report/sixth-assessment-report-cycle/">Core writing team</a></td>
<td>30</td>
<td><a href="https://apps.ipcc.ch/report/authors/report.authors.php?q=38&amp;p=">IPCC authors app</a></td>
</tr>
<tr class="even">
<td>WGI</td>
<td><a href="https://www.ipcc.ch/report/ar6/wg1/about/authors/">Authors page</a></td>
<td>234</td>
<td><a href="https://apps.ipcc.ch/report/authors/report.authors.php?q=35&amp;p=">IPCC authors app</a></td>
</tr>
<tr class="odd">
<td>WGII</td>
<td><a href="https://www.ipcc.ch/report/ar6/wg2/about/authors">Authors page</a></td>
<td>270</td>
<td><a href="https://apps.ipcc.ch/report/authors/report.authors.php?q=36&amp;p=">IPCC authors app</a></td>
</tr>
<tr class="even">
<td>WGIII</td>
<td><a href="https://www.ipcc.ch/report/ar6/wg3/about/authors">Authors page</a></td>
<td>278</td>
<td><a href="https://archive.ipcc.ch/report/authors/report.authors.php?q=37&amp;p=">Archived IPCC authors app</a></td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td><a href="https://www.ipcc.ch/sr15/authors/">Authors page</a></td>
<td>86</td>
<td></td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td><a href="https://www.ipcc.ch/srccl/authors/">Authors page</a></td>
<td>107</td>
<td></td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td><a href="https://www.ipcc.ch/srocc/about/authors/">Authors page</a></td>
<td>~101</td>
<td><a href="https://archive.ipcc.ch/report/authors/report.authors.php?q=33&amp;p=">Archived IPCC authors app</a></td>
</tr>
<tr class="even">
<td><strong>Total (as listed per report)</strong></td>
<td></td>
<td><strong>1,106</strong></td>
<td>Not de-duplicated across reports</td>
</tr>
<tr class="odd">
<td><strong>Total (de-duplicated, June 2026)</strong></td>
<td></td>
<td><strong>932</strong></td>
<td>Deduplicated across all 7 reports</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="wikidata-entries-of-ar6-reports" class="level2">
<h2 class="anchored" data-anchor-id="wikidata-entries-of-ar6-reports">5. Wikidata entries of AR6 reports</h2>
<p><strong>Method</strong></p>
<ul>
<li>Searched Wikidata directly for each report’s name and cross-referenced with <a href="https://scholia.toolforge.org/">Scholia</a>, <a href="https://reasonator.toolforge.org/">Reasonator</a>, and <a href="https://sqid.toolforge.org/">SQID</a>.</li>
<li>Zotero collection: https://www.zotero.org/groups/2437020/semanticclimate/collections/773CNPDW</li>
</ul>
<p><strong>Notes / limitations</strong></p>
<ul>
<li>Wikidata also has entries for parts of reports (e.g.&nbsp;the Summary for Policymakers of the SYR). Only full-report entries are listed here.</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Report</th>
<th>Wikidata item(s)</th>
<th>QID(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IPCC Sixth Assessment Report (overall)</td>
<td>https://www.wikidata.org/wiki/Q103843442</td>
<td>Q103843442</td>
</tr>
<tr class="even">
<td>SYR</td>
<td>https://www.wikidata.org/wiki/Q117820486</td>
<td>Q117820486</td>
</tr>
<tr class="odd">
<td>WGI</td>
<td>https://www.wikidata.org/wiki/Q108133155</td>
<td>Q108133155</td>
</tr>
<tr class="even">
<td>WGII</td>
<td>https://www.wikidata.org/wiki/Q124454848, https://www.wikidata.org/wiki/Q111109497</td>
<td>Q124454848, Q111109497</td>
</tr>
<tr class="odd">
<td>WGIII</td>
<td>https://www.wikidata.org/wiki/Q123285197, https://www.wikidata.org/wiki/Q111489232</td>
<td>Q123285197, Q111489232</td>
</tr>
<tr class="even">
<td>SR1.5</td>
<td>https://www.wikidata.org/wiki/Q57077013, https://www.wikidata.org/wiki/Q123675901</td>
<td>Q57077013, Q123675901</td>
</tr>
<tr class="odd">
<td>SRCCL</td>
<td>https://www.wikidata.org/wiki/Q66310618, https://www.wikidata.org/wiki/Q114750129</td>
<td>Q66310618, Q114750129</td>
</tr>
<tr class="even">
<td>SROCC</td>
<td>https://www.wikidata.org/wiki/Q67028624, https://www.wikidata.org/wiki/Q114204629</td>
<td>Q67028624, Q114204629</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="figures-count" class="level2">
<h2 class="anchored" data-anchor-id="figures-count">6. Figures count</h2>
<p><strong>Method</strong></p>
<ul>
<li>Manually scanned and counted the figure-overview pages published on the IPCC website for each report. Flagged as unreliable; re-counted in the June 2026 update (figures below shown as <code>original → recount</code> where a recount happened).</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Report</th>
<th>Source</th>
<th>Figures</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>https://www.ipcc.ch/report/ar6/syr/figures</td>
<td>28</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>https://www.ipcc.ch/report/ar6/wg1/figures</td>
<td>511 → 515</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>https://www.ipcc.ch/report/ar6/wg2/figures</td>
<td>469</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>https://www.ipcc.ch/report/ar6/wg3/figures</td>
<td>354</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>https://www.ipcc.ch/sr15/graphics/#cid_6333</td>
<td>89</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>Individual chapter links off https://www.ipcc.ch/srccl/ (no consolidated figures repository found)</td>
<td>132 → 116 + 17 images from the PDF-only chapter = 133</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>Individual chapter links off https://www.ipcc.ch/srocc/ (no consolidated figures repository found)</td>
<td>89 → 90</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td><strong>1,672 → 1,678</strong></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="data-count" class="level2">
<h2 class="anchored" data-anchor-id="data-count">7. Data count</h2>
<p>No systematic count of datasets per report has been carried out yet. This section currently records entry points for future quantification work rather than final figures.</p>
<p><strong>Sources identified</strong></p>
<ul>
<li>World Data Center for Climate (WDCC): https://www.wdc-climate.de/ui/q?general_key_ss=IPCC-AR6</li>
<li>IPCC “Available Data for AR6” landing page: https://ipcc-data.org/ar6landing.html</li>
<li>IPCC Data Browser:
<ul>
<li>https://ipcc-browser.ipcc-data.org/browser/search?searchterm=ar6</li>
<li>https://ipcc-browser.ipcc-data.org/browser/search?keywords=IPCC-AR6</li>
<li>https://ipcc-browser.ipcc-data.org/browser/search?keywords=AR6</li>
</ul></li>
<li>Data and code access per report (incomplete): WGI — https://www.ipcc.ch/report/ar6/wg1/resources/data-access/</li>
</ul>
<hr>
</section>
<section id="glossary-term-count" class="level2">
<h2 class="anchored" data-anchor-id="glossary-term-count">8. Glossary term count</h2>
<p><strong>Method</strong></p>
<ul>
<li>Each report PDF contains its own glossary section, but individual reports were not counted separately — instead, the consolidated glossary repository on the IPCC website was used as the source of truth.</li>
<li>The <a href="https://apps.ipcc.ch/glossary/">IPCC Glossary</a> “current terms” view (AR6 Working Group reports only) gives 925 terms in total.</li>
<li>The <a href="https://apps.ipcc.ch/glossary/searchlatest.php">“Past terms”</a> tab additionally surfaces terms from the AR6 Special Reports (SRCCL, SROCC, SR1.5).</li>
<li>June 2026 update: all terms (current + past) were copied into a spreadsheet and merged, adding Working Group attribution to each term. This produced a total of <strong>1,274 terms</strong>.</li>
</ul>
<p><strong>Data files</strong></p>
<ul>
<li>Before merge: <code>Glossary-Full.ods</code> (attached to the source issue)</li>
<li>After merge: <code>Glossary-Full_merged.ods</code> (attached to the source issue)</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Pass</th>
<th>Source</th>
<th>Total terms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Initial</td>
<td>https://apps.ipcc.ch/glossary/ (current terms, WG reports only)</td>
<td>925</td>
</tr>
<tr class="even">
<td>June 2026 (merged)</td>
<td>Current + Past terms, merged and de-duplicated with WG attribution</td>
<td>1,274</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="report-translations" class="level2">
<h2 class="anchored" data-anchor-id="report-translations">9. Report translations</h2>
<p><strong>Method</strong></p>
<ul>
<li>Manually counted the translation files listed on each report’s “Resources / Translations” page. It is not always clear what has actually been translated versus only announced/in preparation, so figures are unreliable and need double-checking.</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Report</th>
<th>Source</th>
<th>Full-report translations</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>https://www.ipcc.ch/report/ar6/syr/resources/translations/</td>
<td>5 (in preparation)</td>
<td>2 × SPM</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>https://www.ipcc.ch/report/ar6/wg1/resources/translations/</td>
<td>5</td>
<td>2, partial</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>https://www.ipcc.ch/report/ar6/wg2/resources/translations/</td>
<td>5</td>
<td>3 × SPM</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>https://www.ipcc.ch/report/ar6/wg3/resources/translations/</td>
<td>5</td>
<td>1 × SPM</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>https://www.ipcc.ch/sr15/download/ (“UN and other languages”)</td>
<td>5</td>
<td>4 × SPM</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>https://www.ipcc.ch/srccl/download/ (“SPM in UN Languages” / “SPM in other languages”)</td>
<td>5 × SPM</td>
<td>3 × SPM</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>https://www.ipcc.ch/srocc/download/ (“UN and other languages”)</td>
<td>5 × SPM</td>
<td>5 × SPM</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="acronyms-count" class="level2">
<h2 class="anchored" data-anchor-id="acronyms-count">10. Acronyms count</h2>
<p><strong>Method</strong></p>
<ul>
<li>Acronym lists were copied from each report’s PDF (typically an annex) into plain text files, then manually corrected for line breaks introduced by the copy/paste. This is not 100% accurate and needs to be automated.</li>
<li>June 2026 update: source data likely came from a prior scrape; the exact scrape method could not be reconstructed. Removing duplicates from the collected spreadsheet gives an approximate total of 1,931 acronyms.</li>
</ul>
<p><strong>Source text files</strong> (extracted from PDFs, attached to the source issue)</p>
<ul>
<li><code>syr-acronyms.txt</code>, <code>wg1-acronyms.txt</code>, <code>wg2-acronyms.txt</code>, <code>wg3-acronyms.txt</code>, <code>SR15-acronyms.txt</code>, <code>SRCCL-acronyms.txt</code>, <code>SROCC-acronyms.txt</code></li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Report</th>
<th>Source</th>
<th>Acronyms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>https://www.ipcc.ch/report/ar6/syr/annexes-and-index/#annex-ii</td>
<td>~90</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>(annex, see acronym text file)</td>
<td>~521</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>https://www.ipcc.ch/report/ar6/wg2/chapter/annex-iii/</td>
<td>~692</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>(annex, see acronym text file)</td>
<td>~548</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>(annex, see acronym text file)</td>
<td>~566</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>(annex, see acronym text file)</td>
<td>~430</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>(annex, see acronym text file)</td>
<td>~194</td>
</tr>
<tr class="even">
<td><strong>De-duplicated total (June 2026)</strong></td>
<td></td>
<td><strong>~1,931</strong></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="index-terms-count" class="level2">
<h2 class="anchored" data-anchor-id="index-terms-count">11. Index terms count</h2>
<p><strong>Method</strong></p>
<ul>
<li>Very rough manual estimates from each report’s index, counted/estimated directly from the PDFs. Explicitly flagged as far from 100% accurate and in need of automation.</li>
<li>Only main (bold) index terms were counted; each of these can have many (sometimes hundreds of) sub-terms that were not counted individually.</li>
</ul>
<p><strong>Data</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Report</th>
<th>Index terms (main/bold terms only)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SYR</td>
<td>~227</td>
</tr>
<tr class="even">
<td>WGI</td>
<td>~1,138</td>
</tr>
<tr class="odd">
<td>WGII</td>
<td>~1,054</td>
</tr>
<tr class="even">
<td>WGIII</td>
<td>~1,005</td>
</tr>
<tr class="odd">
<td>SR1.5</td>
<td>~526</td>
</tr>
<tr class="even">
<td>SRCCL</td>
<td>~1,036</td>
</tr>
<tr class="odd">
<td>SROCC</td>
<td>~477</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="update-log" class="level2">
<h2 class="anchored" data-anchor-id="update-log">Update log</h2>
<ul>
<li><strong>2025-07 to 2025-11</strong>: Initial data collection across all 11 metrics, recorded directly in the source issue by <a href="https://github.com/oldenbourglaura"><span class="citation" data-cites="oldenbourglaura">@oldenbourglaura</span></a>.</li>
<li><strong>2026-06</strong>: Revision pass — corrected page counts (removed double-counted front matter), switched word-count tooling (Chrome “Word Count Counter Plus” extension), re-counted figures, de-duplicated authors (932 total), merged glossary terms (1,274 total), and de-duplicated acronyms (~1,931 total). Licensing/DOI, translations, and index term figures were not updated in this pass.</li>
</ul>
</section>
<section id="open-follow-up-work" class="level2">
<h2 class="anchored" data-anchor-id="open-follow-up-work">Open follow-up work</h2>
<p>Noted by <a href="https://github.com/mrchristian"><span class="citation" data-cites="mrchristian">@mrchristian</span></a> (2025-09-16) as still required:</p>
<ol type="1">
<li>Re-run/validate counts using <a href="https://github.com/kermitt2/grobid">GROBID</a> for structured extraction from the PDFs (tracked in <a href="https://github.com/TIBHannover/climate-knowledge-graph/issues/27">issue #27</a>).</li>
<li>Locate and document the canonical <em>source</em> of each report (status and format — PDF, web, per-language availability, etc.) rather than relying on ad hoc download links.</li>
<li>Establish formal dimensions/quantities for the report corpus (tracked in <a href="https://github.com/TIBHannover/climate-knowledge-graph/issues/23">issue #23</a>, marked as a duplicate of this protocol’s source issue).</li>
<li>Consolidate lists of authors, acronyms, and index terms (tracked in <a href="https://github.com/TIBHannover/climate-knowledge-graph/issues/33">issue #33</a>, completed).</li>
</ol>
<p>Additional reference material: semanticClimate’s listing of AR6 report parts — https://semanticclimate.github.io/p/en/posts/ipcc_resources/, and GERICS’s “IPCC AR6 made easy” summary — https://www.gerics.de/products_and_publications/publications/detail/102556/index.php.en</p>
</section>
<section id="related-repository-content" class="level2">
<h2 class="anchored" data-anchor-id="related-repository-content">Related repository content</h2>
<ul>
<li><a href="../../data/corpus-ar6.html">data/corpus-ar6.html</a> — structural browse page listing AR6 report parts and chapters.</li>
<li><a href="../../datasets.html">datasets.qmd</a> — reports and datasets overview page.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<div class="site-footer-project">
Climate Knowledge Graph is a research and development project from TIB.
</div>
</div>   
    <div class="nav-footer-center">
<nav class="site-footer-nav" aria-label="Footer navigation">
<ul class="site-footer-links">
<li>
<a href="../../about.html">About</a>
</li>
<li>
<a href="../../documentation/test-report-7/incite.html">Our publications</a>
</li>
<li>
<a href="../../roadmap.html">Roadmap</a>
</li>
<li>
<a href="../../change-log.html">Change Log</a>
</li>
<li>
<a href="../../imprint.html">Imprint</a>
</li>
<li>
<a href="../../data-protection.html">Data protection</a>
</li>
<li>
<a href="../../terms-of-use.html">Terms of use</a>
</li>
<li>
<a href="../../accessibility.html">Accessibility</a>
</li>
</ul>
</nav>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>